package northwind.routebuilder.file;

import org.apache.camel.Exchange;
import org.apache.camel.Message;
import org.apache.camel.Processor;
import org.apache.camel.builder.RouteBuilder;

public class OutboundRouteBuilder extends RouteBuilder {

	public static final String FILENAME = "Test_SFTP_Check.txt";
	public static final String FILE_CONTENT = "This file is generated by Apache Camel to check write access";
	public static final String CAMEL_FILE_NAME = "CamelFileName";
	private String start;
	private String uri;
	private String end;

	public OutboundRouteBuilder(String start, String uri, String end) {
		this.start = start;
		this.uri = uri;
		this.end = end;

	}

	@Override
	public void configure() throws Exception {
		from(this.start).to(this.uri).to(this.end);

	}

	public Processor createProcessor() {

		Processor result = new Processor() {
			@Override
			public void process(Exchange exchange) throws Exception {
				Message in = exchange.getIn();
				in.setBody(FILE_CONTENT);
				in.setHeader(CAMEL_FILE_NAME, FILENAME);
			}
		};
		return result;
	}

}
