package com.learnwebservices.services.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2022-08-13T18:21:33.515+05:30
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "HelloEndpointService",
                  wsdlLocation = "https://apps.learnwebservices.com/services/hello?WSDL",
                  targetNamespace = "http://learnwebservices.com/services/hello")
public class HelloEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://learnwebservices.com/services/hello", "HelloEndpointService");
    public final static QName HelloEndpointPort = new QName("http://learnwebservices.com/services/hello", "HelloEndpointPort");
    static {
        URL url = null;
        try {
            url = new URL("https://apps.learnwebservices.com/services/hello?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloEndpointService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://apps.learnwebservices.com/services/hello?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public HelloEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloEndpoint
     */
    @WebEndpoint(name = "HelloEndpointPort")
    public HelloEndpoint getHelloEndpointPort() {
        return super.getPort(HelloEndpointPort, HelloEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloEndpoint
     */
    @WebEndpoint(name = "HelloEndpointPort")
    public HelloEndpoint getHelloEndpointPort(WebServiceFeature... features) {
        return super.getPort(HelloEndpointPort, HelloEndpoint.class, features);
    }

}
