package com.learnwebservices.services.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2022-08-13T18:21:33.461+05:30
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://learnwebservices.com/services/hello", name = "HelloEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloEndpoint {

    @WebMethod(operationName = "SayHello")
    @WebResult(name = "HelloResponse", targetNamespace = "http://learnwebservices.com/services/hello", partName = "HelloResponse")
    public HelloResponse sayHello(

        @WebParam(partName = "HelloRequest", name = "HelloRequest", targetNamespace = "http://learnwebservices.com/services/hello")
        HelloRequest helloRequest
    );
}
